# Define the iOS platform version
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

# Enable Flutter for this project
flutter_ios_podfile_setup

# Main app target
target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!
  
  # Add Bunny Stream SDK modules
  pod 'BunnyStreamAPI', 
    :git => 'https://github.com/BunnyWay/bunny-stream-ios.git', 
    :branch => 'main',
    :inhibit_warnings => true
    
  pod 'BunnyStreamPlayer', 
    :git => 'https://github.com/BunnyWay/bunny-stream-ios.git', 
    :branch => 'main',
    :inhibit_warnings => true
    
  pod 'BunnyStreamUploader', 
    :git => 'https://github.com/BunnyWay/bunny-stream-ios.git', 
    :branch => 'main',
    :inhibit_warnings => true
  
  # Install all Flutter pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # Test target
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
